services:
  app:
    image: gradle:8.7-jdk21
    working_dir: /workspace
    volumes:
      - .:/workspace
      - gradle-cache:/home/gradle/.gradle
    command: sh -lc "./gradlew bootRun -x test --no-daemon"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/beach_complex
      SPRING_DATASOURCE_USERNAME: beach
      SPRING_DATASOURCE_PASSWORD: beach
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: "6379"
volumes:
  gradle-cache:
